[proxmox_hosts]
pve1 ansible_host=192.168.68.84
pve2 ansible_host=192.168.68.85

[debian_vms]
dockerhost ansible_host=192.168.68.100
ollama ansible_host=192.168.68.92

[debian_lxcs]
traefik ansible_host=192.168.68.70

[debian_guests:children]
debian_vms
debian_lxcs

[all:vars]
ansible_user=openclaw
ansible_ssh_private_key_file=/home/martin/.ssh/openclaw_ansible
ansible_become=true
ansible_become_method=sudo
